services:
  - type: web
    name: aaasu-portfolio
    env: node
    buildCommand: npm install && npm run build:server && npm run build
    startCommand: node --experimental-modules server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: aaasu-portfolio
          property: port
    healthCheckPath: /api/health